apiVersion: v1
kind: pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: mpoojithadocker/python-flask:v2
    ports:
    - containerPort: 5000

apiVersion: v1
kind: service
metadata:
  name: my-service
spec:
  type: clusterIp
  selector:
    app: example
  ports:
  - port: 80
    targetPort: 5000
    clusterIp: 31500



